Working with categorical data and organizing them using one hot encoder

Importing libraries

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("housing_categorical_practice.csv")
df

,town,area,price
0,Springfield,1355,317383
1,Springfield,2431,453231
2,Springfield,1567,330162
3,Springfield,1896,348820
4,Riverdale,2608,554642
...,...,...,...
295,Springfield,2378,438308
296,Springfield,2147,411885
297,Riverdale,2241,555049
298,Oakwood,1766,270935


In [3]:
dummies = pd.get_dummies(df['town'], dtype= int)
dummies

,Oakwood,Riverdale,Springfield
0,0,0,1
1,0,0,1
2,0,0,1
3,0,0,1
4,0,1,0
...,...,...,...
295,0,0,1
296,0,0,1
297,0,1,0
298,1,0,0


In [4]:
merged = pd.concat([df,dummies], axis = 'columns')
merged

,town,area,price,Oakwood,Riverdale,Springfield
0,Springfield,1355,317383,0,0,1
1,Springfield,2431,453231,0,0,1
2,Springfield,1567,330162,0,0,1
3,Springfield,1896,348820,0,0,1
4,Riverdale,2608,554642,0,1,0
...,...,...,...,...,...,...
295,Springfield,2378,438308,0,0,1
296,Springfield,2147,411885,0,0,1
297,Riverdale,2241,555049,0,1,0
298,Oakwood,1766,270935,1,0,0


In [5]:
final = merged.drop(['town', 'Oakwood'], axis='columns')
final

,area,price,Riverdale,Springfield
0,1355,317383,0,1
1,2431,453231,0,1
2,1567,330162,0,1
3,1896,348820,0,1
4,2608,554642,1,0
...,...,...,...,...
295,2378,438308,0,1
296,2147,411885,0,1
297,2241,555049,1,0
298,1766,270935,0,0


In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [7]:
X = final.drop('price', axis='columns')
X

,area,Riverdale,Springfield
0,1355,0,1
1,2431,0,1
2,1567,0,1
3,1896,0,1
4,2608,1,0
...,...,...,...
295,2378,0,1
296,2147,0,1
297,2241,1,0
298,1766,0,0


In [8]:
y = final.price
y

0      317383
1      453231
2      330162
3      348820
4      554642
        ...  
295    438308
296    411885
297    555049
298    270935
299    681603
Name: price, Length: 300, dtype: int64

In [9]:
model.fit(X,y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](3,)","[ 123.84,184752.04, 75383.53]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](3,)","['area','Riverdale','Springfield']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,7.076e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,3
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(3)


In [10]:
model.predict(pd.DataFrame(
    [[2800, 1, 0]],
    columns=X.columns
))

array([602263.41480539])

In [11]:
model.score(X,y)

0.9800697834113482

In [29]:
df

,town,area,price
0,2,1355,317383
1,2,2431,453231
2,2,1567,330162
3,2,1896,348820
4,1,2608,554642
...,...,...,...
295,2,2378,438308
296,2,2147,411885
297,1,2241,555049
298,0,1766,270935


In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [14]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

,town,area,price
0,2,1355,317383
1,2,2431,453231
2,2,1567,330162
3,2,1896,348820
4,1,2608,554642
...,...,...,...
295,2,2378,438308
296,2,2147,411885
297,1,2241,555049
298,0,1766,270935


In [15]:
X = dfle[['town', 'area']]. values
X

array([[   2, 1355],
       [   2, 2431],
       [   2, 1567],
       [   2, 1896],
       [   1, 2608],
       [   2, 1436],
       [   1, 1885],
       [   1, 1927],
       [   1, 1899],
       [   2, 1559],
       [   2, 1586],
       [   0, 1646],
       [   2, 2911],
       [   2, 2095],
       [   2, 1396],
       [   2, 1615],
       [   2, 1347],
       [   0, 1196],
       [   2, 2032],
       [   1, 1780],
       [   0,  947],
       [   2, 1357],
       [   1, 2617],
       [   1, 2380],
       [   0, 1848],
       [   1,  890],
       [   2, 1232],
       [   1, 2090],
       [   1, 1805],
       [   2, 1476],
       [   0, 1550],
       [   0, 1241],
       [   0, 1811],
       [   0, 1189],
       [   2, 2309],
       [   0, 1401],
       [   1, 2002],
       [   2, 1735],
       [   1, 1728],
       [   0,  824],
       [   2, 1840],
       [   1, 2103],
       [   2, 1935],
       [   2, 2257],
       [   2, 1479],
       [   1, 2493],
       [   2, 1602],
       [   2,

In [16]:
y = dfle.price
y

0      317383
1      453231
2      330162
3      348820
4      554642
        ...  
295    438308
296    411885
297    555049
298    270935
299    681603
Name: price, Length: 300, dtype: int64

In [17]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [18]:
X = ohe.fit_transform(X).toarray()
X

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.]], shape=(300, 274))

In [19]:
X = X[:,1:]
X

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(300, 273))

In [28]:
model.fit(X,y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](273,)","[ 192006.9 , 75730.32,-170271.77,..., 151958.23, 181750.65, 200060.65]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,2.895e+05
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,273
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(272)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](273,)","[10.52, 5.39, 1.73,..., 0.32, 0.32, 0. ]"


In [22]:
model.fit(final.drop('price', axis='columns'), final.price)

model.predict(pd.DataFrame(
    [[2800, 1, 0]],
    columns=['area', 'Riverdale', 'Springfield']
)) 

array([602263.41480539])

In [23]:
import pickle

In [25]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [26]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [27]:
mp.predict([[5000, 1, 0]])

c:\Users\boogey\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([874707.27921315])